

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build: ./requirements/mariadb
    restart: unless-stopped
    user: root
    networks:
    - inception
    volumes:
    - db:/var/lib/mysql
  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
    - mariadb
    build: ./requirements/wordpress
    restart: unless-stopped
    networks:
    - inception
    volumes:
    - wp:/var/www/
  nginx:
    image: nginx
    container_name: nginx
    env_file: .env
    depends_on:
    - wordpress
    build: ./requirements/nginx
    restart: unless-stopped
    networks:
    - inception
    volumes:
    - wp:/var/www/
    ports:
    - "443:443"

volumes:
  db:
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/pfelipa/data/db
  wp:
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/pfelipa/data/wp

networks:
    inception:

