services:

  mariadb:
    image: mariadb_img
    container_name: mariadb
    env_file: .env
    build: ./requirements/sql
    restart: unless-stopped
    user: root
    networks:
      - inception
    volumes:
      - db:/var/www/

  wordpress:
    image: wordpress_img
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wp:/var/www/

  nginx:
    image: nginx_img
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wp:/var/www/
      # - type: volume
      #   source: wp
      #   target: /home/pfelipa/data/wp
      #   volume:
      #     nocopy: true
    ports:
      - "443:443"

# volumes:
#   db:
#     name: db
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/pfelipa/data/db
#   wp:
#     name: wp
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/pfelipa/data/wp
volumes:
  db:
    external: true
  wp:
    external: true

networks:
    inception:

